=== TiJ-code/ChangelogTool/config-parser/src/main/resources/config.v1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- Legacy/documentation-only declaration. Runtime validation uses config.v1.xsd. -->
<!ELEMENT config (versioning?, archive?, categories?, components?, topics?, breaking.changes?)>
<!ATTLIST config version (1) #REQUIRED>

<!-- Archiving -->
<!ELEMENT archive EMPTY>
<!ATTLIST archive hierarchy (major | major-minor) #IMPLIED>

<!-- Versioning -->
<!ELEMENT versioning (rule+, phases)>
<!ELEMENT rule (filename, version)>
<!ATTLIST rule name CDATA #IMPLIED>
<!ELEMENT filename EMPTY>
<!ATTLIST filename regex CDATA #REQUIRED>
<!ELEMENT version EMPTY>
<!ATTLIST version regex CDATA #REQUIRED>

<!ELEMENT phases (phase+)>
<!ATTLIST phases initial CDATA #IMPLIED release CDATA #IMPLIED>
<!ELEMENT phase (next, prefix?, suffix?, formatter, events?)>
<!ATTLIST phase name CDATA #REQUIRED>
<!ELEMENT next (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT formatter (#PCDATA)>
<!ELEMENT events (event*)>
<!ELEMENT event (major?, minor?, patch?)>
<!ATTLIST event on (phase_entered) #REQUIRED>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT patch (#PCDATA)>

<!-- Categories -->
<!ELEMENT categories (category*)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category name CDATA #REQUIRED>

<!-- Components -->
<!ELEMENT components (component*)>
<!ELEMENT component (component*)>
<!ATTLIST component id CDATA #REQUIRED name CDATA #IMPLIED>

<!-- Topics -->
<!ELEMENT topics (topic*)>
<!ELEMENT topic (component-ref*, topic*)>
<!ATTLIST topic name CDATA #REQUIRED>
<!ELEMENT component-ref EMPTY>
<!ATTLIST component-ref ref CDATA #REQUIRED>

<!-- Breaking changes -->
<!ELEMENT breaking.changes (entry*)>
<!ELEMENT entry (#PCDATA)>

=== TiJ-code/ChangelogTool/config-parser/src/main/resources/config_changelog_tool.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE config SYSTEM "/home/tij/Development/ChangelogTool/config-parser/src/main/resources/config.v1.dtd">
<config version="1">
    <categories>
        <category name="additions">added</category>
        <category name="refactorings">refactored</category>
        <category name="fixes">fixed</category>
        <category name="removals">removed</category>
    </categories>
    <topics>
        <entry>archive</entry>
        <entry>config parser</entry>
        <entry>markdown</entry>
        <entry>patches</entry>
        <entry>versioning</entry>
        <entry>xml-model</entry>
    </topics>
    <breaking.changes>
        <entry>major</entry>
        <entry>minor</entry>
        <entry>trivial</entry>
    </breaking.changes>
</config>
