=== TiJ-code/ChangelogTool/patches/src/main/resources/dtd/config.v1.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT config (categories?, breaking.changes?)>
<!ATTLIST config version CDATA #REQUIRED>

<!ELEMENT categories (entry*)>
<!ELEMENT breaking.changes (entry*)>

<!ELEMENT entry ANY>

=== TiJ-code/ChangelogTool/patches/src/main/resources/config_registermaschine.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE config SYSTEM "config.v1.dtd">
<config version="1">
    <categories>
        <entry>api</entry>
        <entry>core</entry>
        <entry>instructions</entry>
    </categories>
    <breaking.changes>
        <entry>major</entry>
        <entry>minor</entry>
        <entry>trivial</entry>
    </breaking.changes>
</config>
